apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlinesforge-ingress
  namespace: headlinesforge
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: headlinesforge.com
      http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
