"""create core schema

Revision ID: 08d612a102af
Revises: 0f95e46c36cd
Create Date: 2026-05-02 21:57:35.769260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08d612a102af'
down_revision: Union[str, Sequence[str], None] = '0f95e46c36cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('domain_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('kinde_org_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_orgs_domain_name'), 'orgs', ['domain_name'], unique=False)
    op.create_index(op.f('ix_orgs_kinde_org_id'), 'orgs', ['kinde_org_id'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_code', sa.String(length=128), nullable=False),
    sa.Column('author_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('domain_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('html', sa.String(), nullable=True),
    sa.Column('alternative_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('followup_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pipeline_timing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('insufficient_sources_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_code'], ['orgs.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_author', 'articles', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_articles_org_code'), 'articles', ['org_code'], unique=False)
    op.create_index('ix_articles_org_created', 'articles', ['org_code', 'created_at'], unique=False)
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('embed_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embeds_article', 'embed_candidates', ['article_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('was_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_article', 'facts', ['article_id'], unique=False)
    op.create_table('fallback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('failed_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fallback_article', 'fallback_events', ['article_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('speaker', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('was_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_article', 'quotes', ['article_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_article_agent', 'usage_events', ['article_id', 'agent_name'], unique=False)
    op.create_index('ix_usage_occurred', 'usage_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_occurred', table_name='usage_events')
    op.drop_index('ix_usage_article_agent', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_quotes_article', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_fallback_article', table_name='fallback_events')
    op.drop_table('fallback_events')
    op.drop_index('ix_facts_article', table_name='facts')
    op.drop_table('facts')
    op.drop_index('ix_embeds_article', table_name='embed_candidates')
    op.drop_table('embed_candidates')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index('ix_articles_org_created', table_name='articles')
    op.drop_index(op.f('ix_articles_org_code'), table_name='articles')
    op.drop_index('ix_articles_author', table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_orgs_kinde_org_id'), table_name='orgs')
    op.drop_index(op.f('ix_orgs_domain_name'), table_name='orgs')
    op.drop_table('orgs')
    # ### end Alembic commands ###
