"""add_orgconfig_example_titles

Revision ID: 12b602ab7ab5
Revises: e3f4a5b6c7d8
Create Date: 2026-05-04 12:47:19.797793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b602ab7ab5'
down_revision: Union[str, Sequence[str], None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_configs', sa.Column('example_titles', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::text[]'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_configs', 'example_titles')
    # ### end Alembic commands ###
