"""add_article_marked_done_author_email

Revision ID: a3989b3817e8
Revises: f70a4f7ec04a
Create Date: 2026-05-04 11:26:58.940552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3989b3817e8'
down_revision: Union[str, Sequence[str], None] = 'f70a4f7ec04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_email', sa.String(length=256), nullable=True))
    op.add_column('articles', sa.Column('marked_done', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'marked_done')
    op.drop_column('articles', 'author_email')
    # ### end Alembic commands ###
