"""add_org_configs

Revision ID: f70a4f7ec04a
Revises: 08d612a102af
Create Date: 2026-05-03 20:07:14.051525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f70a4f7ec04a'
down_revision: Union[str, Sequence[str], None] = '08d612a102af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_configs',
    sa.Column('org_code', sa.String(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('target_word_count', sa.Integer(), nullable=False),
    sa.Column('max_facts', sa.Integer(), nullable=False),
    sa.Column('max_quotes', sa.Integer(), nullable=False),
    sa.Column('search_freshness', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('num_queries', sa.Integer(), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('min_source_signals', sa.Integer(), nullable=False),
    sa.Column('max_pages_to_scrape', sa.Integer(), nullable=False),
    sa.Column('youtube_search', sa.Boolean(), nullable=False),
    sa.Column('twitter_search', sa.Boolean(), nullable=False),
    sa.Column('facebook_search', sa.Boolean(), nullable=False),
    sa.Column('news_search', sa.Boolean(), nullable=False),
    sa.Column('tiktok_search', sa.Boolean(), nullable=False),
    sa.Column('instagram_search', sa.Boolean(), nullable=False),
    sa.Column('reddit_search', sa.Boolean(), nullable=False),
    sa.Column('media_search_languages', postgresql.ARRAY(sa.String()), server_default=sa.text("ARRAY['en'::text]"), nullable=False),
    sa.Column('media_search_num', sa.Integer(), nullable=False),
    sa.Column('media_search_max_query_tiers', sa.Integer(), nullable=False),
    sa.Column('youtube_sort_by_date', sa.Boolean(), nullable=False),
    sa.Column('reflection_context_articles', sa.Integer(), nullable=False),
    sa.Column('guidelines', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('html_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reflection_stance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example_articles', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['org_code'], ['orgs.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_configs')
    # ### end Alembic commands ###
